In [3]:
import pandas as pd

# Load Data

In [4]:
ecommerce_data = pd.read_csv('ecommerce_data_2.csv')

In [5]:
ecommerce_data.head()

,Order_Date,Time,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product_Category,Product,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_method
0,2018-01-02,10:56:33,8.0,37077,Female,Web,Member,Auto & Accessories,Car Media Players,140.0,1.0,0.3,46.0,4.6,Medium,credit_card
1,2018-07-24,20:41:37,2.0,59173,Female,Web,Member,Auto & Accessories,Car Speakers,211.0,1.0,0.3,112.0,11.2,Medium,credit_card
2,2018-11-08,08:38:49,8.0,41066,Female,Web,Member,Auto & Accessories,Car Body Covers,117.0,5.0,0.1,31.2,3.1,Critical,credit_card
3,2018-04-18,19:28:06,7.0,50741,Female,Web,Member,Auto & Accessories,Car & Bike Care,118.0,1.0,0.3,26.2,2.6,High,credit_card
4,2018-08-13,21:18:39,9.0,53639,Female,Web,Member,Auto & Accessories,Tyre,250.0,1.0,0.3,160.0,16.0,Critical,credit_card

In [8]:
# shape of the data
print("Shape of the data:", ecommerce_data.shape)

Shape of the data: (51290, 17)

In [9]:
# pring unique Customer_Id count
print("Unique Customer_Id count:", ecommerce_data['Customer_Id'].nunique())

Unique Customer_Id count: 38997

# Fix and create some columns

In [6]:
ecommerce_data['OderedDateTime'] = ecommerce_data['Order_Date'] + ' ' + ecommerce_data['Time']
# convert to datetime
ecommerce_data['OderedDateTime'] = pd.to_datetime(ecommerce_data['OderedDateTime'], format='%Y-%m-%d %H:%M:%S')

In [7]:
# count NaN values in each column
nan_counts = ecommerce_data.isna().sum()
# print NaN counts
print(nan_counts)

Order_Date             0
Time                   0
Aging                  1
Customer_Id            0
Gender                 0
Device_Type            0
Customer_Login_type    0
Product_Category       0
Product                0
Sales                  1
Quantity               2
Discount               1
Profit                 0
Shipping_Cost          1
Order_Priority         2
Payment_method         0
OderedDateTime         0
dtype: int64

In [11]:
# just to make sure we have no NaN values in OderedDateTime and CustomerID
ecommerce_data = ecommerce_data.dropna(axis = 0, subset = ['OderedDateTime'])
ecommerce_data = ecommerce_data.dropna(axis = 0, subset = ['Customer_Id'])

In [12]:
ecommerce_data.drop_duplicates(inplace = True)

In [13]:
ecommerce_data

,Order_Date,Time,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product_Category,Product,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_method,OderedDateTime
0,2018-01-02,10:56:33,8.0,37077,Female,Web,Member,Auto & Accessories,Car Media Players,140.0,1.0,0.3,46.0,4.6,Medium,credit_card,2018-01-02 10:56:33
1,2018-07-24,20:41:37,2.0,59173,Female,Web,Member,Auto & Accessories,Car Speakers,211.0,1.0,0.3,112.0,11.2,Medium,credit_card,2018-07-24 20:41:37
2,2018-11-08,08:38:49,8.0,41066,Female,Web,Member,Auto & Accessories,Car Body Covers,117.0,5.0,0.1,31.2,3.1,Critical,credit_card,2018-11-08 08:38:49
3,2018-04-18,19:28:06,7.0,50741,Female,Web,Member,Auto & Accessories,Car & Bike Care,118.0,1.0,0.3,26.2,2.6,High,credit_card,2018-04-18 19:28:06
4,2018-08-13,21:18:39,9.0,53639,Female,Web,Member,Auto & Accessories,Tyre,250.0,1.0,0.3,160.0,16.0,Critical,credit_card,2018-08-13 21:18:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,2018-02-28,22:59:50,6.0,78489,Female,Mobile,Member,Home & Furniture,Shoe Rack,124.0,4.0,0.3,19.2,1.9,Medium,money_order,2018-02-28 22:59:50
51286,2018-02-28,13:19:25,2.0,91941,Female,Mobile,Member,Home & Furniture,Umbrellas,70.0,5.0,0.2,14.0,1.4,Medium,credit_card,2018-02-28 13:19:25
51287,2018-02-28,10:25:07,6.0,63313,Male,Web,Member,Home & Furniture,Dinner Crockery,133.0,1.0,0.3,39.7,4.0,Medium,credit_card,2018-02-28 10:25:07
51288,2018-02-28,10:50:08,7.0,86485,Male,Web,Member,Home & Furniture,Sofa Covers,216.0,1.0,0.2,131.7,13.2,Medium,credit_card,2018-02-28 10:50:08
51289,2018-02-28,11:09:40,5.0,81129,Male,Web,Member,Home & Furniture,Bed Sheets,211.0,5.0,0.3,99.4,9.9,Medium,credit_card,2018-02-28 11:09:40

# Create a pickle file and save it

In [15]:
ecommerce_data.to_pickle('ecommerce_data_2.pkl')